### ISSUE TITLE
Deprecation warning from @octokit/rest

### ISSUE THREAD

**Issue by RappC** [tibdex/github-rebase#14]
When calling `rebasePullRequest` I get warnings like the one below in my logfile as `@octokit/rest` has gone threw major updates since version 16.8.0.

```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".pulls.get()". Use "pull_number" instead
        at Object.keys.forEach.key (/home/sda_admin/DEV/sda-adjutant/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:73:26)
        at Array.forEach (<anonymous>)
        at Object.patchedMethod [as get] (/home/sda_admin/DEV/sda-adjutant/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:69:26)
        at Object.<anonymous> (/home/sda_admin/DEV/sda-adjutant/node_modules/github-rebase/lib/index.js:97:117)
        at Generator.next (<anonymous>)
        at /home/sda_admin/DEV/sda-adjutant/node_modules/github-rebase/lib/index.js:7:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/sda_admin/DEV/sda-adjutant/node_modules/github-rebase/lib/index.js:3:12)
        at Object.rebasePullRequest (/home/sda_admin/DEV/sda-adjutant/node_modules/github-rebase/lib/index.js:95:86)
```

**Comment by tibdex** [comment]
Fixed by #15.
